version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"

    # Auto assign PRs raised to this account on Github
    assignees:
      - "example"

    reviewers:
      - "example"

    # Check for updates to dependencies once a week - Saturday
    schedule:
      interval: "weekly"
      day: "saturday"
